<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartBook.Extensions\SmartBook.Extensions.csproj" />
    <ProjectReference Include="..\SmartBook.Types\SmartBook.Types.csproj" />
  </ItemGroup>

</Project>
